namespace NServiceBus.Community.NanoframeworkMQTT.Tests
{
    /// <summary>The approved public surface of the device assembly, sorted. <c>PublicApiTests</c> compares the assembly with it.</summary>
    internal static class ApprovedPublicApi
    {
        public static readonly string[] Lines = new string[]
        {
            "NServiceBus.CriticalErrorCallback.BeginInvoke(System.String, System.Exception, System.AsyncCallback, System.Object) : System.IAsyncResult",
            "NServiceBus.CriticalErrorCallback.EndInvoke(System.IAsyncResult) : System.Void",
            "NServiceBus.CriticalErrorCallback.Invoke(System.String, System.Exception) : System.Void",
            "NServiceBus.CriticalErrorCallback.ctor(System.Object, System.Int32)",
            "NServiceBus.DeviceEndpoint.Publish(System.Object) : System.Void",
            "NServiceBus.DeviceEndpoint.Publish(System.Object, NServiceBus.PublishOptions) : System.Void",
            "NServiceBus.DeviceEndpoint.Send(System.Object) : System.Void",
            "NServiceBus.DeviceEndpoint.Send(System.Object, NServiceBus.SendOptions) : System.Void",
            "NServiceBus.DeviceEndpoint.Stop() : System.Void",
            "NServiceBus.DeviceEndpoint.Subscribe(System.Type) : System.Void",
            "NServiceBus.DeviceEndpoint.Unsubscribe(System.Type) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.RegisterHandler(System.Type, NServiceBus.IHandleMessages) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.RouteToEndpoint(System.Type, System.String) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.Subscribe(System.Type) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.Unsubscribe(System.Type) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.UseCredentials(System.String, System.String) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.ctor(System.String, System.String, System.Int32)",
            "NServiceBus.DeviceEndpointConfiguration.get_DispatchTimeout() : System.TimeSpan",
            "NServiceBus.DeviceEndpointConfiguration.get_ErrorQueue() : System.String",
            "NServiceBus.DeviceEndpointConfiguration.get_ImmediateRetries() : System.Int32",
            "NServiceBus.DeviceEndpointConfiguration.get_Logger() : Microsoft.Extensions.Logging.ILogger",
            "NServiceBus.DeviceEndpointConfiguration.get_MaximumPacketSize() : System.Int32",
            "NServiceBus.DeviceEndpointConfiguration.get_OnCriticalError() : NServiceBus.CriticalErrorCallback",
            "NServiceBus.DeviceEndpointConfiguration.get_SessionExpiry() : System.TimeSpan",
            "NServiceBus.DeviceEndpointConfiguration.get_StopDrainTimeout() : System.TimeSpan",
            "NServiceBus.DeviceEndpointConfiguration.set_DispatchTimeout(System.TimeSpan) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.set_ErrorQueue(System.String) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.set_ImmediateRetries(System.Int32) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.set_Logger(Microsoft.Extensions.Logging.ILogger) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.set_MaximumPacketSize(System.Int32) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.set_OnCriticalError(NServiceBus.CriticalErrorCallback) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.set_SessionExpiry(System.TimeSpan) : System.Void",
            "NServiceBus.DeviceEndpointConfiguration.set_StopDrainTimeout(System.TimeSpan) : System.Void",
            "NServiceBus.IHandleMessages.Handle(System.Object, NServiceBus.IMessageHandlerContext) : System.Void",
            "NServiceBus.IMessageHandlerContext.Publish(System.Object) : System.Void",
            "NServiceBus.IMessageHandlerContext.Publish(System.Object, NServiceBus.PublishOptions) : System.Void",
            "NServiceBus.IMessageHandlerContext.Reply(System.Object) : System.Void",
            "NServiceBus.IMessageHandlerContext.Reply(System.Object, NServiceBus.ReplyOptions) : System.Void",
            "NServiceBus.IMessageHandlerContext.Send(System.Object) : System.Void",
            "NServiceBus.IMessageHandlerContext.Send(System.Object, NServiceBus.SendOptions) : System.Void",
            "NServiceBus.IMessageHandlerContext.get_MessageHeaders() : System.Collections.Hashtable",
            "NServiceBus.IMessageHandlerContext.get_MessageId() : System.String",
            "NServiceBus.IMessageHandlerContext.get_ReplyToAddress() : System.String",
            "NServiceBus.IMessageSession.Publish(System.Object) : System.Void",
            "NServiceBus.IMessageSession.Publish(System.Object, NServiceBus.PublishOptions) : System.Void",
            "NServiceBus.IMessageSession.Send(System.Object) : System.Void",
            "NServiceBus.IMessageSession.Send(System.Object, NServiceBus.SendOptions) : System.Void",
            "NServiceBus.IMessageSession.Subscribe(System.Type) : System.Void",
            "NServiceBus.IMessageSession.Unsubscribe(System.Type) : System.Void",
            "NServiceBus.PublishOptions.SetHeader(System.String, System.String) : System.Void",
            "NServiceBus.PublishOptions.ctor()",
            "NServiceBus.ReplyOptions.SetHeader(System.String, System.String) : System.Void",
            "NServiceBus.ReplyOptions.ctor()",
            "NServiceBus.SendOptions.SetHeader(System.String, System.String) : System.Void",
            "NServiceBus.SendOptions.ctor()",
            "NServiceBus.SendOptions.get_Destination() : System.String",
            "NServiceBus.SendOptions.set_Destination(System.String) : System.Void",
            "class NServiceBus.DeviceEndpoint : NServiceBus.IMessageSession",
            "class NServiceBus.DeviceEndpointConfiguration",
            "class NServiceBus.PublishOptions",
            "class NServiceBus.ReplyOptions",
            "class NServiceBus.SendOptions",
            "delegate NServiceBus.CriticalErrorCallback",
            "interface NServiceBus.ICommand : NServiceBus.IMessage",
            "interface NServiceBus.IEvent : NServiceBus.IMessage",
            "interface NServiceBus.IHandleMessages",
            "interface NServiceBus.IMessage",
            "interface NServiceBus.IMessageHandlerContext",
            "interface NServiceBus.IMessageSession",
            "static NServiceBus.DeviceEndpoint.Start(NServiceBus.DeviceEndpointConfiguration) : NServiceBus.DeviceEndpoint",
        };
    }
}
